spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mbrconabil@gmail.com
spring.mail.password=rwwl xztc pgrw hsnf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=http://localhost:4200